name: Secrets Scan

on:
  workflow_call:
  #push:
  #pull_request:
  #workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2 # acción oficial que corre el binario de Gitleaks
        with:
          args: detect --source . --no-git --redact

          #detect --source: escanea el repo actual.
          #--no-git: ignora el historial completo y solo revisa la snapshot actual (opcional, si quieres todo el historial, quítalo).
          #--redact: enmascara los secrets encontrados para que no se muestren completos en los logs
