name: Download Image + Container Signing + Push Registry

on:
  workflow_call:
    inputs:
      registry:
        description: "Container registry (ghcr.io, docker.io, ...)"
        required: true
        type: string
      image_name:
        description: "Image name (org/repo o usuario/imagen)"
        required: true
        type: string
      image_tag:
        description: "Tag de la imagen (normalmente el SHA del commit o fecha)"
        required: true
        type: string
    secrets:
      # Opcionales: solo se usan si registry != ghcr.io
      REGISTRY_USERNAME:
        required: false
      REGISTRY_PASSWORD:
        required: false

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  sign:
    runs-on: ubuntu-latest
    env:
      IMAGE_REF: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Load image from artifact
        run: |
          docker load -i docker-image.tar
          docker images

      - name: Define IMAGE_REF
        run: echo "IMAGE_REF=${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}" >> $GITHUB_ENV

      - name: Docker login
        env:
          REGISTRY: ${{ inputs.registry }}
          USERNAME: ${{ secrets.REGISTRY_USERNAME || github.actor }}
          PASSWORD: ${{ secrets.REGISTRY_PASSWORD || secrets.GITHUB_TOKEN }}
        run: |
          echo "$PASSWORD" | docker login "$REGISTRY" -u "$USERNAME" --password-stdin
          
      - name: Push image
        run: docker push "${IMAGE_REF}"

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.6.0

      - name: Cosign sign (keyless via OIDC)
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign --yes "${IMAGE_REF}"

      - name: Verify signature (optional)
        continue-on-error: true
        run: cosign verify "${IMAGE_REF}"
