name: Container Signing

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write  # para cosign keyless (Fulcio/OIDC)
  packages: write # para push a GHCR
  contents: read

jobs:
  cosign-sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      # Log in to GHCR
      - name: Log in to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      # Build de la imagen (si no viene ya construida del job anterior)
      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/tfm-app:${{ github.sha }}
          docker build -t $IMAGE -f src/docker/Dockerfile .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      # Push image to GHCR
      - name: Push image
        run: docker push $IMAGE

        # Get image digest
      - name: Get image digest
        id: dig
        run: |
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE)
          echo "DIGEST=$DIGEST" >> $GITHUB_ENV
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT
        
      # Instalar cosign
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.5.0

      # Firmar imagen con Cosign (keyless usando OIDC de GitHub)
      - name: Sign container image
        run: |
          cosign sign --yes $DIGEST
