name: Docker Build

on:
  workflow_dispatch:
  workflow_call:
  
    inputs:
      registry:   { required: true, type: string }
      image_name: { required: true, type: string }
      image_tag:  { required: true, type: string }
      image_tar:  { required: true, type: string }
    #secrets:
      #REGISTRY_USERNAME: { required: true }
      #REGISTRY_PASSWORD: { required: true }

permissions:
  contents: read
  packages: write

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          IMAGE_REF="${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}"
          docker build -t "$IMAGE_REF" -f src/docker/Dockerfile .

      - name: Save image to tar
        run: |
          IMAGE_REF="${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}"
          docker save "$IMAGE_REF" -o "${{ inputs.image_tar }}"

      - name: Upload docker artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ${{ inputs.image_tar }}
