name: Docker Build
on:
  workflow_call:
    inputs:
      registry: {required: true, type: string}
      image_name: {required: true, type: string}
      image_tag: {required: true, type: string}
      image_tar: {required: true, type: string}
    secrets:
      REGISTRY_USERNAME: {required: true}
      REGISTRY_PASSWORD: {required: true}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login \
            ${{ inputs.registry }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
      - run: docker build -t ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }} .
      - run: docker save ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }} -o ${{ inputs.image_tar }}
      - uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ${{ inputs.image_tar }}
