name: Download Docker Artifact
on:
  workflow_call:
    inputs:
      image_tar: {required: true, type: string}
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .
      - run: docker load -i ${{ inputs.image_tar }}
