name: Image Scan

on:
  workflow_call:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Construcción de la imagen Docker del proyecto
      - name: Build Docker image
        run: |
          docker build -t TFM-app:latest .

      # Escaneo de la imagen con Trivy
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0 # Accion oficial de Trivy
        with:
          image-ref: TFM-app:latest # Lo he llamado TFM-app aqui y en el build, puede cambiarse
          format: table
          exit-code: 1   # Falla si se encuentran vulnerabilidades
          vuln-type: 'os,library' # Escanea paquetes del sistema y librerias
          severity: 'CRITICAL,HIGH' # Severidades consideradas como bloqueantes
