name: Image Scan
on:
  workflow_call:
    inputs:
      registry: {required: true, type: string}
      image_name: {required: true, type: string}
      image_tag: {required: true, type: string}
jobs:
  image-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
          format: 'table'
          exit-code: '0'
          severity: 'HIGH,CRITICAL'
          vuln-type: 'os,library'
          scanners: 'vuln,secret'
          output: 'image-trivy.txt'
      - uses: actions/upload-artifact@v4
        with:
          name: image-trivy-report
          path: image-trivy.txt

