name: DevSecOps Pipeline

on:
  workflow_dispatch:

jobs:
  secrets-scan:
    uses: ./Secrets_Scan.yml

  sca:
    needs: secrets-scan
    uses: ./SCA.yml

  sast:
    uses: ./SAST.yml

  image-scan:
    uses: ./Image_Scan.yml

  container-signing:
    needs: image-scan
    uses: ./Container_Signing.yml

  iac-security:
    uses: ./IaC_Security.yml
