name: DevSecOps Pipeline

on:
  workflow_dispatch:

jobs:
  secrets-scan:
    uses: ./.github/workflows/Secrets_Scan.yml

  sca:
    needs: secrets-scan
    uses: ./.github/workflows/SCA.yml

  sast:
    needs: sca
    uses: ./.github/workflows/SAST.yml

  image-scan:
    needs: sast,sca
    uses: ./.github/workflows/Image_Scan.yml

  container-signing:
    needs: image-scan
    uses: ./.github/workflows/Container_Signing.yml

  iac-security:
    needs: container-signing
    uses: ./.github/workflows/IaC_Security.yml
