name: Push Signed Image
on:
  workflow_call:
    inputs:
      registry: {required: true, type: string}
      image_name: {required: true, type: string}
      image_tag: {required: true, type: string}
    secrets:
      REGISTRY_USERNAME: {required: true}
      REGISTRY_PASSWORD: {required: true}
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login \
            ${{ inputs.registry }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
      - run: docker push ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
