name: Step 2.2 - SAST 

on:
  # Para lanzarlo manualmente desde la interfaz de Actions
  workflow_dispatch:
  # Para ser llamado desde el pipeline orquestador
  workflow_call:

jobs:
  semgrep-sast:
    name: Semgrep SAST Analysis
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write   # necesario para subir SARIF a la pestaña de Security

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep SAST
        run: semgrep scan --sarif --config auto . > semgrep-results.sarif || true

      - name: Upload SARIF results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sast-results
          path: semgrep-results.sarif

      - name: Upload SARIF to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif
