name: Secrets Scan (OSS - Windows)

on:
  workflow_dispatch:
  # push:
  # pull_request:

jobs:
  gitleaks:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Gitleaks (OSS)
        shell: powershell
        run: |
          $ProgressPreference = 'SilentlyContinue'
          $zipUrl = "https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_windows_x64.zip"
          Invoke-WebRequest -Uri $zipUrl -OutFile gitleaks.zip
          Expand-Archive -Path gitleaks.zip -DestinationPath .
          echo "$pwd" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Run Gitleaks scan
        shell: powershell
        run: |
          .\gitleaks.exe detect --source . --report-path gitleaks-report.json --report-format json --verbose || exit 0

      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
          if-no-files-found: ignore
