name: Secrets Scan

on:
  workflow_call:
  workflow_dispatch:
  #push:
  #pull_request:

permissions:
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2 # acción oficial que corre el binario de Gitleaks
        with:
          args: detect --source . --no-git --verbose
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
