name: Step 1 - Secrets Scan # Nombre del workflow que podremos visualizar en la pestaña de 'Actions' posteriormente cuando se ejecute.

on: # Define cuando debe ejecutarse el workflow.
  workflow_call: # Permite que otros workflows puedan llamarlo desde el mismo repositorio o desde repositorios diferentes.
    secrets: # Define qué secretos se deben proporcionar al invocar este workflow.
      gitleaks_license: # Define el secreto que tenemos guardado en el repositorio con la licencia de GitLeaks.
        # Indicamos que es obligatorio proporcionar este secreto cuando se llama al workflow.
        required: true
  workflow_dispatch: # Permite ejecutarlo manualmente desde la interfaz de GitHub.
  
jobs: # Se usa para definir uno o más trabajos (independientes o secuenciales) a ejecutar. Cada job puede tener uno o varios steps, independientes o secuenciales (needs), y correr en entornos distintos (Ubuntu, Windows, MacOS).
  scan: # Este nombre se usa como ID interno del job para poder referenciarlo o establecer dependencias (needs) en otros jobs.
    name: gitleaks # Se usa para asignar un nombre legible a este job, que se mostrará en la interfaz de GitHub Actions.
    runs-on: ubuntu-latest # Runner (máquina virtual) donde se va a ejecutar este job.
    permissions: # Define los permisos que GitHub le da al workflow en tiempo de ejecución.
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    steps: # Se usa para definir uno o más pasos que se deben ejecutar, de manera independiente o secuencial, para realizar el job.
      - uses: actions/checkout@v4 # Acción oficial para descargarnos el código del repositorio en el runner de GitHub Actions para que los siguientes steps tengan acceso a el.
        with: # En este caso necesitaremos pasar unos parámetros de configuración personalizada para que pueda lanzar correctamente el escaneo.
          fetch-depth: 0 # Indicamos que debe clonar todo el historial completo del repositorio, ya que, por defecto, checkout solo descarga el último commit para ahorrar tiempo y espacio.
      - uses: gitleaks/gitleaks-action@v2.3.9 # Usamos la acción oficial de GitHub para ejecutar GitLeaks.
        continue-on-error: true
        env: # Se usa para declarar las variables de entorno que se pasarán a la acción.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Pasa el token de autenticación que GitHub Actions genera automáticamente para cada ejecución.
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Pasa el secreto que contiene la licencia de Gitleaks.
          GITLEAKS_VERSION: latest # Le indica a la acción de Gitleaks que use la versión más reciente disponible de la herramienta.

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3 # Accion oficial de Github para subir informes en formato SARIF, generados por el step anterior, al Security Dashboard.
        if: success() || failure() # De esta manera siempre se subirán los resultados al Security Dashboard, falle o no. Fallar significa que el workflow devuelva un código de error distinto a 0.
        with:
          sarif_file: results.sarif # Nombre del archivo donde se guardan los resultados al finalizar el escaneo de secretos.
