# 
# Reference from:
# https://www.aquasec.com/blog/devsecops-with-trivy-github-actions/

# Name of the security step
name: Step 3 - Image Scan

# Environment variables
env:
  IMAGE_NAME: "tfm-app:latest"
  TRIVY_SEVERITY: "CRITICAL,HIGH"
  TRIVY_VULN_TYPE: "os,library"

# When is it going to activate
on:
  # On demand
  workflow_call:
  # And when the father calls
  workflow_dispatch:

# What is going to do
jobs:
  # Name of the job
  trivy-scan:
    # Machine of GitHub - Microsoft 
    runs-on: ubuntu-latest
    # Steps:
    #  1. Download repo on the VM
    #  2. Build docker
    #  3. Scan the docker with trivy
    steps:
      #  1. Download repo on the VM
      - name: Checkout repo
        uses: actions/checkout@v4
      #  2. Build docker
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME -f /src/docker/Dockerfile .
      #  3. Scan the docker with trivy
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: $IMAGE_NAME
          format: table
          exit-code: 1
          vuln-type: $TRIVY_VULN_TYPE
          severity: $TRIVY_SEVERITY
